#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

j=1

while [ $j -le 10 ]
do
    echo "Best School"
    if [ $j -eq 9 ]
    then
        echo "Hi"
    fi
    ((j++))
done
