#!/usr/bin/env bash
# A script that loops through 1 to 10 using while, if, elif and else 

j=1

while [ $j -le 10 ]
do
    if [ $j -eq 4 ]
    then
        echo "bad luck"
    elif [ $j -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((j++))
done
